# Generated by Django 3.2.24 on 2024-02-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagementsystem', '0005_auto_20240210_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='datamanagementsystem.entity'),
        ),
    ]
