# Generated by Django 3.2.24 on 2024-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagementsystem', '0007_auto_20240211_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_value',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
